### ISSUE TITLE
SPARQL-DL API doesn't support datatypes (strings)

### ISSUE THREAD

**Issue by andreabellandi** [protegeproject/sparql-dl-api#3]
I'm using SPARQL-DL with OWL-API in a Java application. The Maven dependency is the following:
```xml
<dependency>
    <groupId>edu.stanford.protege</groupId>
    <artifactId>de-derivo-sparqldlapi</artifactId>
    <version>2.0.0</version>
</dependency>
```
I assume it downloads the right (compatible) version of OWL-API. I have a class Person with some individuals. Each individual has a data property called name which ranges over a string. The ontology is the following:
```xml
<?xml version="1.0"?>

<!DOCTYPE Ontology [
    <!ENTITY xsd "http://www.w3.org/2001/XMLSchema#" >
    <!ENTITY xml "http://www.w3.org/XML/1998/namespace" >
    <!ENTITY rdfs "http://www.w3.org/2000/01/rdf-schema#" >
    <!ENTITY rdf "http://www.w3.org/1999/02/22-rdf-syntax-ns#" >
]>

<Ontology xmlns="http://www.w3.org/2002/07/owl#"
     xml:base="http://www.semanticweb.org/andrea/ontologies/2016/10/untitled-ontology-83"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:xml="http://www.w3.org/XML/1998/namespace"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
     ontologyIRI="http://www.semanticweb.org/andrea/ontologies/2016/10/untitled-ontology-83">
    <Prefix name="owl" IRI="http://www.w3.org/2002/07/owl#"/>
    <Prefix name="rdf" IRI="http://www.w3.org/1999/02/22-rdf-syntax-ns#"/>
    <Prefix name="xsd" IRI="http://www.w3.org/2001/XMLSchema#"/>
    <Prefix name="rdfs" IRI="http://www.w3.org/2000/01/rdf-schema#"/>
    <Declaration>
        <Class IRI="#Person"/>
    </Declaration>
    <Declaration>
        <DataProperty IRI="#name"/>
    </Declaration>
    <Declaration>
        <NamedIndividual IRI="#t"/>
    </Declaration>
    <ClassAssertion>
        <Class IRI="#Person"/>
        <NamedIndividual IRI="#t"/>
    </ClassAssertion>
    <DataPropertyAssertion>
        <DataProperty IRI="#name"/>
        <NamedIndividual IRI="#t"/>
        <Literal datatypeIRI="&xsd;string">Andrea</Literal>
    </DataPropertyAssertion>
    <DataPropertyRange>
        <DataProperty IRI="#name"/>
        <Datatype abbreviatedIRI="xsd:string"/>
    </DataPropertyRange>
</Ontology>
```

By running this query:
`SELECT ?x WHERE { PropertyValue(?y, my:name, ?x) }`
I get this:
`?de.derivo.sparqldlapi.Var@78 = ?"Andrea"^^xsd:string`

I'm not able to get the individual, called t, having name equal to Andrea.
`SELECT ?p WHERE { PropertyValue(?p, my:name, "Andrea") } `
returns an empty set 
and
`SELECT ?p WHERE { PropertyValue(?p, my:name, "Andrea^^xsd:string") }`
returns an empty set.

`SELECT ?y WHERE { PropertyValue(?y, my:name, "Pluto"^^xsd:string) }`
returns this error:
Character ")" awaited in SPARQL-DL query. (near "^^xsd:string", pos: 344, col: 52, row: 6)

How can I retrieve ontology individuals having a datatype property equal to a specific string value by using SPARQL-DL?

**Comment by matthewhorridge** [comment]
I've only done a quick and dirty test for this using the Protege SNAP-SPARQL plugin (which uses this SPARQL-DL under the hood).  Both

```ttl
SELECT ?p WHERE {
	?p :name "Andrea"
}
```
and the equivalent
```ttl
SELECT ?p WHERE {
	?p :name "Andrea"^^xsd:string
}
```
work as expected and return t in the result set.

How are you executing the query and what does your code look like?

**Comment by andreabellandi** [comment]
I attach 1) my java test class and the related pom.xml, and 2)  my toy ontology.
[Test.java.txt](https://github.com/protegeproject/sparql-dl-api/files/624020/Test.java.txt)
[pom.xml.txt](https://github.com/protegeproject/sparql-dl-api/files/624022/pom.xml.txt)
[ontoProva.owl.txt](https://github.com/protegeproject/sparql-dl-api/files/624023/ontoProva.owl.txt)

Could you please check if I'm wrong?
Thanks in advance,
Andrea

**Comment by matthewhorridge** [comment]
Hi Andrea,

Without running it, but looking at your source code, my first thought is that you need to use an actual OWL reasoner (e.g. FaCT++, HermiT, Pellet, ELK etc.) and not the structural reasoner.  Please could you try this?

**Comment by andreabellandi** [comment]
Hi Matthew,
I tried to use HermiT but (I attach Test java class):
1) SELECT ?p WHERE { PropertyValue(?p, my:name, "Andrea") }
returns an empty set;
2) SELECT ?p WHERE { PropertyValue(?p, my:name, "Andrea^^xsd:string") }
returns: "Character ")" awaited in SPARQL-DL query. (near "^^xsd:string", pos: 345, col: 53, row: 6)"
I did not test any other reasoners (fact++, pellet), because they commit me to use owl-api versions too old....

[Test.java.txt](https://github.com/protegeproject/sparql-dl-api/files/627721/Test.java.txt)

**Comment by matthewhorridge** [comment]
Hi Andrea,

It looks like the parsing of literals is incorrect in the SPARQL-DL library.  The string "Andrea" is parsed and the literal that is created includes the double quotes in the lexical value of the literal.  i.e. the parsed value is ""Andrea""^^xsd:string.  I'll see if I can fix this.

**Comment by matthewhorridge** [comment]
Just another point in this.... 
You should use this dependency for HermiT (which works with the latest versions of the OWL API)

```xml
<dependency>
            <groupId>net.sourceforge.owlapi</groupId>
            <artifactId>org.semanticweb.hermit</artifactId>
            <version>1.3.8.413</version>
</dependency>
```

**Comment by matthewhorridge** [comment]
> SELECT ?p WHERE { PropertyValue(?p, my:name, "Andrea^^xsd:string") }
returns: "Character ")" awaited in SPARQL-DL query. (near "^^xsd:string", pos: 345, col: 53, row: 6)"

I don't think this datatype syntax is supported in the SPARQL-DL syntax here.

**Comment by matthewhorridge** [comment]
I've fixed the parser issue.  It now returns the expected results.  Note that explicit typing with ^^xsd:string is not supported in this syntax.
